on: [ pull_request ]

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v4
    - name: Run style checks
      uses: coleaeason/actions-uncrustify@v1
